[2025-08-28T03:29:06.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T03:29:06.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [queued]>
[2025-08-28T03:29:06.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [queued]>
[2025-08-28T03:29:06.152+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-28T03:29:06.160+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_new_file> on 2025-08-28 02:00:00+00:00
[2025-08-28T03:29:06.165+0000] {standard_task_runner.py:63} INFO - Started process 181 to run task
[2025-08-28T03:29:06.168+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres', 'wait_for_new_file', 'scheduled__2025-08-28T02:00:00+00:00', '--job-id', '527', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres.py', '--cfg-path', '/tmp/tmp64radexi']
[2025-08-28T03:29:06.169+0000] {standard_task_runner.py:91} INFO - Job 527: Subtask wait_for_new_file
[2025-08-28T03:29:06.181+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T03:29:06.206+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [running]> on host c3d91d0460b0
[2025-08-28T03:29:06.269+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T02:00:00+00:00'
[2025-08-28T03:29:06.270+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T03:29:06.397+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7ff845fbbe20>
[2025-08-28T03:30:06.621+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7ff845fbbe20>
[2025-08-28T03:31:06.659+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7ff845fbbe20>
[2025-08-28T03:31:06.685+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2025-08-28T03:31:06.685+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T03:31:06.692+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=minio_to_postgres, task_id=wait_for_new_file, run_id=scheduled__2025-08-28T02:00:00+00:00, execution_date=20250828T020000, start_date=20250828T032906, end_date=20250828T033106
[2025-08-28T03:31:06.738+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-28T03:31:06.760+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-28T03:31:06.761+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-28T03:55:05.049+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T03:55:05.067+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [queued]>
[2025-08-28T03:55:05.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [queued]>
[2025-08-28T03:55:05.072+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-28T03:55:05.080+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): wait_for_new_file> on 2025-08-28 02:00:00+00:00
[2025-08-28T03:55:05.085+0000] {standard_task_runner.py:63} INFO - Started process 1043 to run task
[2025-08-28T03:55:05.087+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'minio_to_postgres', 'wait_for_new_file', 'scheduled__2025-08-28T02:00:00+00:00', '--job-id', '625', '--raw', '--subdir', 'DAGS_FOLDER/minio_to_postgres.py', '--cfg-path', '/tmp/tmpmtied55m']
[2025-08-28T03:55:05.089+0000] {standard_task_runner.py:91} INFO - Job 625: Subtask wait_for_new_file
[2025-08-28T03:55:05.100+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-28T03:55:05.125+0000] {task_command.py:426} INFO - Running <TaskInstance: minio_to_postgres.wait_for_new_file scheduled__2025-08-28T02:00:00+00:00 [running]> on host c3d91d0460b0
[2025-08-28T03:55:05.180+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='minio_to_postgres' AIRFLOW_CTX_TASK_ID='wait_for_new_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-28T02:00:00+00:00'
[2025-08-28T03:55:05.181+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T03:55:05.189+0000] {python.py:75} INFO - Poking callable: <function check_new_file at 0x7ff845fbbe20>
[2025-08-28T03:55:05.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T03:55:05.373+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sensors/python.py", line 76, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/minio_to_postgres.py", line 34, in check_new_file
    for page in pages:
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2025-08-28T03:55:05.381+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=minio_to_postgres, task_id=wait_for_new_file, run_id=scheduled__2025-08-28T02:00:00+00:00, execution_date=20250828T020000, start_date=20250828T035505, end_date=20250828T035505
[2025-08-28T03:55:05.395+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 625 for task wait_for_new_file (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 1043)
[2025-08-28T03:55:05.420+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T03:55:05.444+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T03:55:05.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
